### PR TITLE
Chris/feature/contact us

### PR DESCRIPTION
**Pull request by RiceChrissy**
- [x] undated tasks page
- [ ] contact us page

image

image

### CODE REVIEW

**Comment by devnamme** [comment]
looks like there is a slight problem with the events card. let's fix it during beta!

are you going to add more commits here or should i merge it now? there are some delays with beta testing

**Comment by RiceChrissy** [comment]
I’m planning to work on the contact us page later on this branch so I might commit again here late at night or tomorrow; tho you can merge this now and I’ll make another request after I finished the contact us.

**Comment by devnamme** [comment]
will merge after na lang!

**Comment by devnamme** [comment]
will merge this now! have to start prepping for beta. please make another PR for the contact us page after this one

**Pull request merged**
