### PR TITLE
Chris/feature/empty screen pages

### PR DESCRIPTION
**Pull request by devnamme**

### CODE REVIEW

**Comment by devnamme** [comment]
@RiceChrissy comment + add here

**Comment by RiceChrissy** [comment]
- [ ] QPI Screen > Year and Dropdown Component
- [x] Empty screens (Schedule, QPI, Calendar, Home Screen, Main Screen,)
- [x] Bottom Nav Bar Widget
- [ ] Splash Screen
image

image

**Comment by devnamme** [comment]
please don't merge right after opening, try to follow this:
1. open pull request and add comments (screenshots)
    - pull request should always be directed to `develop` first and not `main`
    - you can edit the branch later on if you chose the wrong one (only for the one who opened the PR)
2. wait for reviews/comments (for revisions)
    - you can assign a reviewers or mention me (type `@dnamme` in comments)
    image
3. fix in the same branch
4. merge once approved

some comments about these:
- switch to [google_fonts](https://pub.dev/packages/google_fonts), as far as i know, we're using DM Sans
- `runApp()` should be in `lib/main.dart` (default in flutter), specific screens are in `lib/screens/...`
- nav bar font style should be consistent (active font size is bigger than unselected)
    - try using `selectedLabelStyle` and `unselectedLabelStyle` in the [BottomNavigationBar class](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html)

i can add screenshots for some of these later, especially the `runApp()`. for now, you can work on these in a separate branch (perhaps `chris/fix/...?`) next week/tomorrow

**Comment by devnamme** [comment]
on second thought, i'll fix the file structure later. please check it tonight or tomorrow for the changes and branch out from there ^^

**Comment by RiceChrissy** [comment]
I apologize for this, it's my first time using GitHub like this so I hope to have your patience.

**Comment by devnamme** [comment]
all good!! i'm also learning about how this stuff works haha. but good job! ^^

**Pull request merged**
